version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/project/
    networks:
      - symfony

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/project/
    networks:
      - symfony

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD: "root"
      - MYSQL_DATABASE: "database"
    ports:
      - 3311:3306
    networks:
      - symfony

networks:
  symfony:
